### ISSUE TITLE
chrome is showing its malicious

### ISSUE THREAD

**Issue by Akash-Informationnews** [utsanjan/InsiderSwitch#1]

**Comment by utsanjan** [comment]
This is occurring due to some false positives, otherwise the file is totally clean, and yes I swear it'll not harm any PC untill and unless it's used in the right version of Windows (use only in Windows 11)

**Comment by Suleman-Elahi** [comment]
https://www.virustotal.com/gui/file/387e7d7526c2558ec80e5425207231878c7b69cb7ae45778bfc6eb16f51c0115 

virus alert
